// menu
export const SHOW_HIDE_MENU = 'SHOW_HIDE_MENU';
export const HIDE_MENU = 'HIDE_MENU';

// report/access
export const FETCH_ACCESS_TABLE = 'FETCH_ACCESS_TABLE';
export const FETCH_ACCESS_TABLE_REQUEST = 'FETCH_ACCESS_TABLE_REQUEST';
export const FETCH_ACCESS_TABLE_SUCCESS = 'FETCH_ACCESS_TABLE_SUCCESS';
export const FETCH_ACCESS_TABLE_FAILURE = 'FETCH_ACCESS_TABLE_FAILURE';
export const CLEAR_ACCESS_TABLE = 'CLEAR_ACCESS_TABLE';

// report/operational
export const FETCH_OPERATIONAL_TABLE = 'FETCH_OPERATIONAL_TABLE';
export const FETCH_OPERATIONAL_TABLE_REQUEST =
  'FETCH_OPERATIONAL_TABLE_REQUEST';
export const FETCH_OPERATIONAL_TABLE_SUCCESS =
  'FETCH_OPERATIONAL_TABLE_SUCCESS';
export const FETCH_OPERATIONAL_TABLE_FAILURE =
  'FETCH_OPERATIONAL_TABLE_FAILURE';
export const CLEAR_OPERATIONAL_TABLE = 'CLEAR_OPERATIONAL_TABLE';

// ipAddress
export const FETCH_IP_ADDRESS_TABLE = 'FETCH_IP_ADDRESS_TABLE';
export const FETCH_IP_ADDRESS_TABLE_REQUEST = 'FETCH_IP_ADDRESS_TABLE_REQUEST';
export const FETCH_IP_ADDRESS_TABLE_SUCCESS = 'FETCH_IP_ADDRESS_TABLE_SUCCESS';
export const FETCH_IP_ADDRESS_TABLE_FAILURE = 'FETCH_IP_ADDRESS_TABLE_FAILURE';
export const CLEAR_IP_ADDRESS_TABLE = 'CLEAR_IP_ADDRESS_TABLE';

export const ADD_IP_ADDRESS = 'ADD_IP_ADDRESS';
export const ADD_IP_ADDRESS_REQUEST = 'ADD_IP_ADDRESS_REQUEST';
export const ADD_IP_ADDRESS_SUCCESS = 'ADD_IP_ADDRESS_SUCCESS';
export const ADD_IP_ADDRESS_FAILURE = 'ADD_IP_ADDRESS_FAILURE';

export const DELETE_IP_ADDRESS = 'DELETE_IP_ADDRESS';
export const DELETE_IP_ADDRESS_REQUEST = 'DELETE_IP_ADDRESS_REQUEST';
export const DELETE_IP_ADDRESS_SUCCESS = 'DELETE_IP_ADDRESS_SUCCESS';
export const DELETE_IP_ADDRESS_FAILURE = 'DELETE_IP_ADDRESS_FAILURE';
