// menu
export const SHOW_HIDE_MENU = 'SHOW_HIDE_MENU';
export const HIDE_MENU = 'HIDE_MENU';

// report/access
export const FETCH_ACCESS_TABLE = 'FETCH_ACCESS_TABLE';
export const FETCH_ACCESS_TABLE_REQUEST = 'FETCH_ACCESS_TABLE_REQUEST';
export const FETCH_ACCESS_TABLE_SUCCESS = 'FETCH_ACCESS_TABLE_SUCCESS';
export const FETCH_ACCESS_TABLE_FAILURE = 'FETCH_ACCESS_TABLE_FAILURE';
export const CLEAR_ACCESS_TABLE = 'CLEAR_ACCESS_TABLE';

// report/operational
export const FETCH_OPERATIONAL_TABLE = 'FETCH_OPERATIONAL_TABLE';
export const FETCH_OPERATIONAL_TABLE_REQUEST =
  'FETCH_OPERATIONAL_TABLE_REQUEST';
export const FETCH_OPERATIONAL_TABLE_SUCCESS =
  'FETCH_OPERATIONAL_TABLE_SUCCESS';
export const FETCH_OPERATIONAL_TABLE_FAILURE =
  'FETCH_OPERATIONAL_TABLE_FAILURE';
export const CLEAR_OPERATIONAL_TABLE = 'CLEAR_OPERATIONAL_TABLE';
