// menu
export const SHOW_HIDE_MENU = 'SHOW_HIDE_MENU';
export const HIDE_MENU = 'HIDE_MENU';

// report/access
export const FETCH_ACCESS_TABLE = 'FETCH_ACCESS_TABLE';
export const FETCH_ACCESS_TABLE_REQUEST = 'FETCH_ACCESS_TABLE_REQUEST';
export const FETCH_ACCESS_TABLE_SUCCESS = 'FETCH_ACCESS_TABLE_SUCCESS';
export const FETCH_ACCESS_TABLE_FAILURE = 'FETCH_ACCESS_TABLE_FAILURE';
export const CLEAR_ACCESS_TABLE = 'CLEAR_ACCESS_TABLE';

// report/operational
export const FETCH_OPERATIONAL_TABLE = 'FETCH_OPERATIONAL_TABLE';
export const FETCH_OPERATIONAL_TABLE_REQUEST =
  'FETCH_OPERATIONAL_TABLE_REQUEST';
export const FETCH_OPERATIONAL_TABLE_SUCCESS =
  'FETCH_OPERATIONAL_TABLE_SUCCESS';
export const FETCH_OPERATIONAL_TABLE_FAILURE =
  'FETCH_OPERATIONAL_TABLE_FAILURE';
export const CLEAR_OPERATIONAL_TABLE = 'CLEAR_OPERATIONAL_TABLE';

// ipAddress
export const FETCH_IP_ADDRESS_TABLE = 'FETCH_IP_ADDRESS_TABLE';
export const FETCH_IP_ADDRESS_TABLE_REQUEST = 'FETCH_IP_ADDRESS_TABLE_REQUEST';
export const FETCH_IP_ADDRESS_TABLE_SUCCESS = 'FETCH_IP_ADDRESS_TABLE_SUCCESS';
export const FETCH_IP_ADDRESS_TABLE_FAILURE = 'FETCH_IP_ADDRESS_TABLE_FAILURE';
export const CLEAR_IP_ADDRESS_TABLE = 'CLEAR_IP_ADDRESS_TABLE';

export const ADD_IP_ADDRESS = 'ADD_IP_ADDRESS';
export const ADD_IP_ADDRESS_REQUEST = 'ADD_IP_ADDRESS_REQUEST';
export const ADD_IP_ADDRESS_SUCCESS = 'ADD_IP_ADDRESS_SUCCESS';
export const ADD_IP_ADDRESS_FAILURE = 'ADD_IP_ADDRESS_FAILURE';

export const DELETE_IP_ADDRESS = 'DELETE_IP_ADDRESS';
export const DELETE_IP_ADDRESS_REQUEST = 'DELETE_IP_ADDRESS_REQUEST';
export const DELETE_IP_ADDRESS_SUCCESS = 'DELETE_IP_ADDRESS_SUCCESS';
export const DELETE_IP_ADDRESS_FAILURE = 'DELETE_IP_ADDRESS_FAILURE';

// workflow/ordem
export const FETCH_STATUS_ORDER = 'FETCH_STATUS_ORDER';
export const FETCH_STATUS_ORDER_REQUEST = 'FETCH_STATUS_ORDER_REQUEST';
export const FETCH_STATUS_ORDER_SUCCESS = 'FETCH_STATUS_ORDER_SUCCESS';
export const FETCH_STATUS_ORDER_FAILURE = 'FETCH_STATUS_ORDER_FAILURE';

export const CHANGE_STATUS_ORDER = 'CHANGE_STATUS_ORDER';
export const CHANGE_STATUS_ORDER_REQUEST = 'CHANGE_STATUS_ORDER_REQUEST';
export const CHANGE_STATUS_ORDER_SUCCESS = 'CHANGE_STATUS_ORDER_SUCCESS';
export const CHANGE_STATUS_ORDER_FAILURE = 'CHANGE_STATUS_ORDER_FAILURE';

// workflow/matriz
export const FETCH_WORKFLOW_PRODUCT = 'FETCH_WORKFLOW_PRODUCT';
export const FETCH_WORKFLOW_PRODUCT_REQUEST = 'FETCH_WORKFLOW_PRODUCT_REQUEST';
export const FETCH_WORKFLOW_PRODUCT_SUCCESS = 'FETCH_WORKFLOW_PRODUCT_SUCCESS';
export const FETCH_WORKFLOW_PRODUCT_FAILURE = 'FETCH_WORKFLOW_PRODUCT_FAILURE';

export const DELETE_WORKFLOW_PRODUCT = 'DELETE_WORKFLOW_PRODUCT';
export const DELETE_WORKFLOW_PRODUCT_REQUEST =
  'DELETE_WORKFLOW_PRODUCT_REQUEST';
export const DELETE_WORKFLOW_PRODUCT_SUCCESS =
  'DELETE_WORKFLOW_PRODUCT_SUCCESS';
export const DELETE_WORKFLOW_PRODUCT_FAILURE =
  'DELETE_WORKFLOW_PRODUCT_FAILURE';

export const ADD_PERMISSION = 'ADD_PERMISSION';
export const ADD_PERMISSION_REQUEST = 'ADD_PERMISSION_REQUEST';
export const ADD_PERMISSION_SUCCESS = 'ADD_PERMISSION_SUCCESS';
export const ADD_PERMISSION_FAILURE = 'ADD_PERMISSION_FAILURE';

// resource/action
export const FETCH_ACTION = 'FETCH_ACTION';
export const FETCH_ACTION_REQUEST = 'FETCH_ACTION_REQUEST';
export const FETCH_ACTION_SUCCESS = 'FETCH_ACTION_SUCCESS';
export const FETCH_ACTION_FAILURE = 'FETCH_ACTION_FAILURE';

export const ADD_ACTION = 'ADD_ACTION';
export const ADD_ACTION_REQUEST = 'ADD_ACTION_REQUEST';
export const ADD_ACTION_SUCCESS = 'ADD_ACTION_SUCCESS';
export const ADD_ACTION_FAILURE = 'ADD_ACTION_FAILURE';

export const DELETE_ACTION = 'DELETE_ACTION';
export const DELETE_ACTION_REQUEST = 'DELETE_ACTION_REQUEST';
export const DELETE_ACTION_SUCCESS = 'DELETE_ACTION_SUCCESS';
export const DELETE_ACTION_FAILURE = 'DELETE_ACTION_FAILURE';

// resource/system
export const FETCH_SYSTEM = 'FETCH_SYSTEM';
export const FETCH_SYSTEM_REQUEST = 'FETCH_SYSTEM_REQUEST';
export const FETCH_SYSTEM_SUCCESS = 'FETCH_SYSTEM_SUCCESS';
export const FETCH_SYSTEM_FAILURE = 'FETCH_SYSTEM_FAILURE';

export const ADD_SYSTEM = 'ADD_SYSTEM';
export const ADD_SYSTEM_REQUEST = 'ADD_SYSTEM_REQUEST';
export const ADD_SYSTEM_SUCCESS = 'ADD_SYSTEM_SUCCESS';
export const ADD_SYSTEM_FAILURE = 'ADD_SYSTEM_FAILURE';

export const DELETE_SYSTEM = 'DELETE_SYSTEM';
export const DELETE_SYSTEM_REQUEST = 'DELETE_SYSTEM_REQUEST';
export const DELETE_SYSTEM_SUCCESS = 'DELETE_SYSTEM_SUCCESS';
export const DELETE_SYSTEM_FAILURE = 'DELETE_SYSTEM_FAILURE';

// users
export const FETCH_USERS = 'FETCH_USERS';
export const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_FAILURE = 'FETCH_USERS_FAILURE';

// profile/account
export const FETCH_ACCOUNT_DATA = 'FETCH_ACCOUNT_DATA';
export const FETCH_ACCOUNT_DATA_REQUEST = 'FETCH_ACCOUNT_DATA_REQUEST';
export const FETCH_ACCOUNT_DATA_SUCCESS = 'FETCH_ACCOUNT_DATA_SUCCESS';
export const FETCH_ACCOUNT_DATA_FAILURE = 'FETCH_ACCOUNT_DATA_FAILURE';

// profile/report access
export const FETCH_REPORT_ACCESS_TABLE = 'FETCH_REPORT_ACCESS_TABLE';
export const FETCH_REPORT_ACCESS_TABLE_REQUEST =
  'FETCH_REPORT_ACCESS_TABLE_REQUEST';
export const FETCH_REPORT_ACCESS_TABLE_SUCCESS =
  'FETCH_REPORT_ACCESS_TABLE_SUCCESS';
export const FETCH_REPORT_ACCESS_TABLE_FAILURE =
  'FETCH_REPORT_ACCESS_TABLE_FAILURE';
export const CLEAR_REPORT_ACCESS_TABLE = 'CLEAR_REPORT_ACCESS_TABLE';

// profile/personal data
export const FETCH_PERSONAL_DATA = 'FETCH_PERSONAL_DATA';
export const FETCH_PERSONAL_DATA_REQUEST = 'FETCH_PERSONAL_DATA_REQUEST';
export const FETCH_PERSONAL_DATA_SUCCESS = 'FETCH_PERSONAL_DATA_SUCCESS';
export const FETCH_PERSONAL_DATA_FAILURE = 'FETCH_PERSONAL_DATA_FAILURE';

export const SAVE_PERSONAL_DATA = 'FETCH_ACCOUNT_DATA';
export const SAVE_PERSONAL_DATA_REQUEST = 'SAVE_PERSONAL_DATA_REQUEST';
export const SAVE_PERSONAL_DATA_SUCCESS = 'SAVE_PERSONAL_DATA_SUCCESS';
export const SAVE_PERSONAL_DATA_FAILURE = 'SAVE_PERSONAL_DATA_FAILURE';
